spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.csaetfddt6jh.ap-northeast-2.rds.amazonaws.com:13306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: ${MYSQL_SECRET}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
config:
  domain:

cloud:
  aws:
    s3:
      bucket: eunjeongsoloproject
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: ${JWT_SECRET_KEY}               # 민감한 정보는 시스템 환경 변수설정
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420