spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
      mode: always
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        use_sql_comments: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
cloud:
  aws:
    s3:
      bucket: eunjeongsoloproject
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

mail:
  address:
    admin: admin@gmail.com
jwt:
  key: ${JWT_SECRET_KEY}               # 민감한 정보는 시스템 환경 변수설정
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G_CLIENT_ID}
            clientSecret: ${G_CLIENT_SECRET}
            scope:
              - email
              - profile

